baseURL = "https://vassily60.github.io/"
languageCode = "en-us"
title = "Vassily Lombard Blog"
theme = "PaperMod"

[params]
  author = "Vassily Lombard"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  math = true
